# -*- coding: utf-8 -*-
"""Datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oVzX3ti_6pCmc9Pl1fYh3gn5USCXa59n
"""

# Importar las librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

# Commented out IPython magic to ensure Python compatibility.
# Esta linea permite que los gráficos sean renderizados directamente en neustro Notebook 
## Cargar datos en un pandas dataframe traer base de datos
# %matplotlib inline

"""**Cargar datos en un pandas dataframe traer base de datos**"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/MyDrive/python/datos/datosp'
!ls

dir = '/content/drive/MyDrive/python/datos/datosp/{}'.format('datosp.csv')

data = pd.read_csv(dir, encoding='utf-8')

data.head()

type(data)

# visaulizamos las columnas
  data.columns

data.index

columna1 = data['movie_title']
columna1.head()

linea = data.loc[10,:]
linea

data.loc[:,'movie_title'].head()

data.info

# columnas númericas y columnas de texto
type(data.dtypes)

data.dtypes

data.dtypes == float

data.dtypes == int

(data.dtypes == float) | (data.dtypes == int)

data.dtypes == object

num = (data.dtypes == float) | (data.dtypes == int)
num

num.index

for el in num:
  print(el)

for el in num.index:
  print(el)

num_cols = [c for c in num.index if num[c]]

num_cols

obj = (data.dtypes == object)
obj_cols = [c for c in obj.index if num[c]]

obj_cols

data[num_cols]

data_num = data[num_cols]
data_num

data_num.describe()

"""Para hacer nuestro primer modelo más simple para este trabajaremos csolo con las columnas númericas"""

data_num['duration'].hist()

data_num['imdb_score'].hist()

data_num['budget'].hist()

(data_num['budget'] > 1000000)

(data_num['budget'] > 1000000).value_counts()

mask = (data_num['budget'] > 1000000)
mask

data[mask]

