# -*- coding: utf-8 -*-
"""Datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oVzX3ti_6pCmc9Pl1fYh3gn5USCXa59n
"""

# Importar las librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

# Commented out IPython magic to ensure Python compatibility.
# Esta linea permite que los gráficos sean renderizados directamente en neustro Notebook 
## Cargar datos en un pandas dataframe traer base de datos
# %matplotlib inline

"""**Cargar datos en un pandas dataframe traer base de datos**"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/MyDrive/python/datos/datosp'
!ls

dir = '/content/drive/MyDrive/python/datos/datosp/{}'.format('datosp.csv')

data = pd.read_csv(dir, encoding='utf-8')

data.head()

type(data)

# visaulizamos las columnas
  data.columns

data.index

columna1 = data['movie_title']
columna1.head()

linea = data.loc[10,:]
linea

data.loc[:,'movie_title'].head()

