# -*- coding: utf-8 -*-
"""PredecirIngresos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qR5wzwnI-Hj4_hHQGLPBPaA9kh-xpSwg
"""

#Importar la librería
import numpy as np

a1 = np.array([1,2,3])
a1

type(a1)

a2 = np.arange(10)
a2

a3 = np.zeros((2,3))
a3

a4 = np.ones((2,3))
a4

from IPython.display import display
display(a3); display(a4)

a5 = np.linspace(1,1,11)
a5

a5.dtype

a1.shape

a2.shape

a3.shape

a4.shape

a5.shape

a1D = np.array([1,2,3])
a2D = np.array([[1,2,3]])
display(a1D.shape)
display(a2D.shape)

# son los dos array iguales
np.array_equal(a1D, a2D)

# Reshaping
new_dims = (1, a1D.shape[0])
a = a1D.reshape(new_dims)

np.array_equal(a, a2D)

